### ISSUE TITLE
Not working at all in 3.8.2

### ISSUE THREAD

**Issue by RvRoo** [margusholland/Comma#8] opened 2016-05-27 08:02 UTC
The plugin is not working at all. I get the following error in my Console:

```
27/05/16 08:42:53,940 Title Case (Sketch Plugin)[5365]: TypeError: doc.selectedLayersOfClass is not a function. (In 'doc.selectedLayersOfClass(MSTextLayer)', 'doc.selectedLayersOfClass' is undefined)
line: 4
sourceURL: [redacted]
Support/com.bohemiancoding.sketch3/Plugins/Comma/Comma.sketchplugin/Contents/Sketch/script.cocoascript
column: 50
```

**Comment by margusholland** [comment] 2016-05-27 10:32
Duplicate of #7

**Closed as completed by margusholland** 2016-05-27 10:32 UTC
